image:
  - Ubuntu1804

branches:
  only:
    - master

build:
  verbosity: detailed

install:
  - cwd=`pwd`
  - cd ..
  - git clone https://github.com/hpb-htw/wikinary-eintopf.git
  - echo $cwd
  - cd $cwd
  - ls ../wikinary-eintopf.git


build_script:
  - make refresh install bin

on_success:
  - echo "Done"
  - pwd
  - make coverage/lcov.info
  - ls coverage
  - bash <(curl -s https://codecov.io/bash) -f  coverage/lcov.info



