image:
  - Ubuntu1804

branches:
  only:
    - master

install:
  - git clone https://github.com/hpb-htw/wikinary-eintopf.git ../wikinary-eintopf
  - ls ../wikinary-eintopf

build:
  verbosity: detailed

build_script:
  - make refresh install bin

on_success:
  - echo "Done"
  - pwd
  - make coverage/lcov.info
  - ls coverage
  - bash <(curl -s https://codecov.io/bash) -f  coverage/lcov.info



